import type { NextPage } from 'next'
import {useEffect, useState} from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { supabase } from '../util/supabaseClient';
import { User } from '@supabase/supabase-js';
import Router from 'next/router';

const Home: NextPage = () => {
  const [user, setUser] = useState<User | null>(null);

  async function getProfile(id:string){
    try {
      let {data , error, status} = await supabase.from('profiles').select('username').eq('id', id).single
      console.log(data, error, status);
      if(!data){
        Router.push('/profile')
      }
    } catch (error) {
      console.log(error);
    }
  }


  async function getUser(){
    try {
      const user = await supabase.auth.user();
      if(!user) {
        Router.push('/login');
      }
      setUser(user)
    } catch (error) {
      
    }
  } 

  useEffect(() =>{
    getUser();
  } , []);

  useEffect(() => {
    if(user){
      getProfile(user.id);
    }
  }, [user])

  
  console.log(supabase.auth.user())
  return (
    <div className={styles.container}>
      <Head>
        <title>Supachat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Welcome to Supa-Chat</h1>
        {user && <div>Welcome {user.email}</div>}
      </div>

    </div>
  )
}

export default Home
